### ISSUE TITLE
failure in ratcheting_session_alice_initialize can go unnoticed

### ISSUE THREAD

**Issue by Smattr** [WhisperSystems/libsignal-protocol-c#54]
This function calls `session_state_add_receiver_chain` that can fail with OOM. The call is made on a branch which can result in 0 being returned from `ratcheting_session_alice_initialize`. I would fix this myself by checking the return value from `session_state_add_receiver_chain`, but it's not clear if we can just bail out at this point. It's past the point of commit (the `complete` label) which makes me think we're in an inconsistent state here. Do you have a suggested fix? Apologies if I've misdiagnosed what's going on here.

**Comment by dkonigsberg** [comment]
This is a good catch. I'll take it as a to-do to investigate further and fix when I have the time.
Most likely the solution will be to rearrange things so that state update block occurs before the "complete" label, and that the "add" function is done first. But I'll obviously have to make sure its done in such a way that bailing is indeed safe.

**Comment by Smattr** [comment]
Oh nice! I failed to notice `session_state_add_receiver_chain` is orthogonal from these other ops such that they can be reordered. As always, love your work, @dkonigsberg.
